### ISSUE TITLE
when check devops pipeline 

### ISSUE THREAD

**Issue by dafanshu** [kubesphere/ks-devops#715] opened 2022-07-04 03:51 UTC
**Describe the Bug**
Get "http://devops-jenkins.kubesphere-devops-system/crumbIssuer/api/json/api/json": dial tcp 10.233.55.175:80: connect: connection refused

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: v3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by LinuxSuRen** [comment] 2022-07-04 08:23
I guess this problem caused by the deployment of Jenkins has health issues. Please feel free to check it and any possible log output.

By the way, the default JVM setting of Jenkins is pretty low. Please give it a reasonable value according to your situation.

/kind support

**Comment by LinuxSuRen** [comment] 2022-07-04 08:24
See also https://github.com/kubesphere/kubesphere/issues/5014

**Comment by LinuxSuRen** [comment] 2022-07-13 10:05
I'm going to close this issue due to no more information provided from @dafanshu . Please feel free to reopen this if you still have trouble with this.
/close

**Closed by LinuxSuRen** 2022-07-13 10:05 UTC
Labels: kind/bug, kind/support, triage/needs-information
